# Generated by Django 4.1 on 2023-08-27 05:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sample",
            options={"verbose_name": "サンプル", "verbose_name_plural": "00.サンプル"},
        ),
    ]
